# Generated by Django 4.0.5 on 2022-06-27 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biller',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('item_name', models.CharField(max_length=20, unique=True)),
                ('item_category', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('item_subcategory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
